/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.LinkedList;

/**
 *
 * @author nieves
 */
public class Ganancias extends javax.swing.JFrame {

    /**
     * Creates new form Ganancias
     */
    String mes(int i){
        String ret = "";
        switch(i){
            case 1:
                ret =  "enero";
                break;
            case 2:
                ret = "febrero";
                break;
            case 3:
                ret = "marzo";
                break;
            case 4:
                ret = "abril";
                break;
            case 5:
                ret = "mayo";
                break;
            case 6:
                ret = "junio";
                break;
            case 7:
                ret = "julio";
                break;
            case 8:
                ret = "agosto";
                break;
            case 9:
                ret = "septiembre";
                break;
            case 10:
                ret = "octubre";
                break;
            case 11:
                ret = "noviembre";
                break;
            case 12:
                ret = "diciembre";
                break;
        }
        return ret;
    }
    public Ganancias(LinkedList<String[]> ganancias) {
        initComponents();
        jTextArea1.append("Tus ganancias fueron las siguientes\n");
        Iterator<String[]> it = ganancias.iterator();
        String[] temp; 
        while(it.hasNext()){
            temp = it.next();
            jTextArea1.append(String.format("Tus ganacias del mes de %s del año %s fueron %s pesos\n",mes(Integer.parseInt(temp[1])),temp[0],temp[2]));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
