\copy vehiculo FROM '/home/nieves/proyecto_bases/proyecto_bases/vehiculo.csv' WITH (DELIMITER ',');
\copy socio FROM '/home/nieves/proyecto_bases/proyecto_bases/socio.csv' WITH (DELIMITER ',');
\copy cliente FROM '/home/nieves/proyecto_bases/proyecto_bases/cliente.csv' WITH (DELIMITER ',');
\copy dueno FROM '/home/nieves/proyecto_bases/proyecto_bases/dueno.csv' WITH (DELIMITER ',');
\copy chofer FROM '/home/nieves/proyecto_bases/proyecto_bases/chofer.csv' WITH (DELIMITER ',');
\copy agente FROM '/home/nieves/proyecto_bases/proyecto_bases/agente.csv' WITH (DELIMITER ',');
\copy taxi FROM '/home/nieves/proyecto_bases/proyecto_bases/taxi.csv' WITH (DELIMITER ',');
\copy multa FROM '/home/nieves/proyecto_bases/proyecto_bases/multa.csv' WITH (DELIMITER ',');
\copy aseguradora FROM '/home/nieves/proyecto_bases/proyecto_bases/aseguradora.csv' WITH (DELIMITER ',');
\copy seguro FROM '/home/nieves/proyecto_bases/proyecto_bases/seguro.csv' WITH (DELIMITER ',');
\copy taxi_baja FROM '/home/nieves/proyecto_bases/proyecto_bases/taxi_baja.csv' WITH (DELIMITER ',');
\copy viaje FROM '/home/nieves/proyecto_bases/proyecto_bases/viaje.csv' WITH (DELIMITER ',');
\copy transaccion FROM '/home/nieves/proyecto_bases/proyecto_bases/transaccion.csv' WITH (DELIMITER ',');
-- \copy ganancia FROM '/home/nieves/proyecto_bases/proyecto_bases/ganancia.csv' WITH (DELIMITER ',');
